Contextualização
Imagine que você está responsável por auxiliar o João do time sourcing a determinar quais transportadoras parceiras serão designadas para atender regiões determinadas do país. João precisa saber qual concorrente é mais competitivo segundo os fatores: custo e tempo de entrega.

Para realizar a análise você acessou o banco da Shopee e coletou uma pequena amostra dos nossos pedidos, que junto as tabelas de custos e prazos de cada transportador te auxiliarão na resolução do problema.

As tabelas do fornecedor a e b estão por faixa de CEP, e as colunas “0.1, 0.25, 0.3...” são os valores que os fornecedores cobram por peso (referente a sua respectiva coluna) em Quilogramas. Na amostra de pedidos cada ID é referente a um pedido saindo do SOC de Santana para o CEP indicado.

In [1]:
import pandas as pd

In [32]:
#carries_a = pd.read_csv('carrier_a_prices.csv')
carries_a[(48000129 >= carries_a['ini_CEP']) & (48000129 <= carries_a['fim_CEP'])]  
#carries_a.head(20)

Empty DataFrame
Columns: [ini_CEP, fim_CEP, lead_time, 0.1, 0.25, 0.3, 0.5, 0.75, 1, 1.25, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5, 6, 7, 7.5, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
Index: []

[0 rows x 44 columns]

In [3]:
carries_b = pd.read_csv('carrier_b_prices.csv')
carries_b.head(20)

,ini_CEP,fim_CEP,lead_time,0.1,0.25,0.3,0.5,0.75,1,1.25,...,21,22,23,24,25,26,27,28,29,30
0,1000001,1099999,2,6.7488,6.7488,6.7488,6.7488,6.7488,6.7488,7.406688,...,43.738367,46.464552,49.213144,51.991612,54.792487,57.630707,60.483865,63.374368,66.287278,69.222595
1,1100000,1156958,2,6.7488,6.7488,6.7488,6.7488,6.7488,6.7488,7.406688,...,43.738367,46.464552,49.213144,51.991612,54.792487,57.630707,60.483865,63.374368,66.287278,69.222595
2,1156959,1156969,2,6.7488,6.7488,6.7488,6.7488,6.7488,6.7488,7.406688,...,43.738367,46.464552,49.213144,51.991612,54.792487,57.630707,60.483865,63.374368,66.287278,69.222595
3,1156970,1199999,2,6.7488,6.7488,6.7488,6.7488,6.7488,6.7488,7.406688,...,43.738367,46.464552,49.213144,51.991612,54.792487,57.630707,60.483865,63.374368,66.287278,69.222595
4,1200000,1233999,2,6.7488,6.7488,6.7488,6.7488,6.7488,6.7488,7.406688,...,43.738367,46.464552,49.213144,51.991612,54.792487,57.630707,60.483865,63.374368,66.287278,69.222595
5,1234000,1234000,2,6.7488,6.7488,6.7488,6.7488,6.7488,6.7488,7.406688,...,43.738367,46.464552,49.213144,51.991612,54.792487,57.630707,60.483865,63.374368,66.287278,69.222595
6,1234001,1234019,2,6.7488,6.7488,6.7488,6.7488,6.7488,6.7488,7.406688,...,43.738367,46.464552,49.213144,51.991612,54.792487,57.630707,60.483865,63.374368,66.287278,69.222595
7,1234020,1234969,2,6.7488,6.7488,6.7488,6.7488,6.7488,6.7488,7.406688,...,43.738367,46.464552,49.213144,51.991612,54.792487,57.630707,60.483865,63.374368,66.287278,69.222595
8,1234970,1234999,2,6.7488,6.7488,6.7488,6.7488,6.7488,6.7488,7.406688,...,43.738367,46.464552,49.213144,51.991612,54.792487,57.630707,60.483865,63.374368,66.287278,69.222595
9,1235000,1237999,2,6.7488,6.7488,6.7488,6.7488,6.7488,6.7488,7.406688,...,43.738367,46.464552,49.213144,51.991612,54.792487,57.630707,60.483865,63.374368,66.287278,69.222595
10,1238000,1246099,2,6.7488,6.7488,6.7488,6.7488,6.7488,6.7488,7.406688,...,43.738367,46.464552,49.213144,51.991612,54.792487,57.630707,60.483865,63.374368,66.287278,69.222595
11,1246100,1246109,2,6.7488,6.7488,6.7488,6.7488,6.7488,6.7488,7.406688,...,43.738367,46.464552,49.213144,51.991612,54.792487,57.630707,60.483865,63.374368,66.287278,69.222595
12,1246110,1246129,2,6.7488,6.7488,6.7488,6.7488,6.7488,6.7488,7.406688,...,43.738367,46.464552,49.213144,51.991612,54.792487,57.630707,60.483865,63.374368,66.287278,69.222595
13,1246130,1246139,2,6.7488,6.7488,6.7488,6.7488,6.7488,6.7488,7.406688,...,43.738367,46.464552,49.213144,51.991612,54.792487,57.630707,60.483865,63.374368,66.287278,69.222595
14,1246140,1247009,2,6.7488,6.7488,6.7488,6.7488,6.7488,6.7488,7.406688,...,43.738367,46.464552,49.213144,51.991612,54.792487,57.630707,60.483865,63.374368,66.287278,69.222595
15,1247010,1247069,2,6.7488,6.7488,6.7488,6.7488,6.7488,6.7488,7.406688,...,43.738367,46.464552,49.213144,51.991612,54.792487,57.630707,60.483865,63.374368,66.287278,69.222595
16,1247070,1247999,2,6.7488,6.7488,6.7488,6.7488,6.7488,6.7488,7.406688,...,43.738367,46.464552,49.213144,51.991612,54.792487,57.630707,60.483865,63.374368,66.287278,69.222595
17,1248000,1248019,2,6.7488,6.7488,6.7488,6.7488,6.7488,6.7488,7.406688,...,43.738367,46.464552,49.213144,51.991612,54.792487,57.630707,60.483865,63.374368,66.287278,69.222595
18,1248020,1248029,2,6.7488,6.7488,6.7488,6.7488,6.7488,6.7488,7.406688,...,43.738367,46.464552,49.213144,51.991612,54.792487,57.630707,60.483865,63.374368,66.287278,69.222595
19,1248030,1248079,2,6.7488,6.7488,6.7488,6.7488,6.7488,6.7488,7.406688,...,43.738367,46.464552,49.213144,51.991612,54.792487,57.630707,60.483865,63.374368,66.287278,69.222595

In [4]:
 pedidos = pd.read_csv('sample.csv')
pedidos.head(20)

,DATE_TIME,ID,STATE,CITY,ZIPCODE,WEIGHT(g)
0,2022-04-11 04:41:39.000,103369596292271,São Paulo,Pirassununga,13638405,176.00
1,2022-04-06 12:16:06.000,102958488529312,São Paulo,Praia Grande,11701230,1050.00
2,2022-04-17 18:54:41.000,103933822246771,São Paulo,Bauru,17051-080,100.00
3,2022-04-06 19:06:49.000,102990666261835,Minas Gerais,Tapiraí,38985000,1334.00
4,2022-04-13 21:55:05.000,103598769058125,São Paulo,São Paulo,03258030,1000.00
5,2022-04-18 06:18:51.000,103980705243736,Rio Grande do Sul,Vespasiano Correa,95972000,70.00
6,2022-04-13 08:19:32.000,103553319086609,Minas Gerais,Montes Claros,39402218,562.99
7,2022-04-12 02:12:18.000,103445836489925,Minas Gerais,Itanhandu,37464000,352.00
8,2022-04-06 22:29:07.000,102994528489070,São Paulo,Poá,08554120,400.00
9,2022-04-11 10:32:16.000,103388782855299,Espírito Santo,Linhares,29909290,1000.00
10,2022-04-09 20:11:29.000,103252314981747,Rondônia,Porto Velho,76810-420,176.00
11,2022-04-14 02:31:20.000,103615312575804,São Paulo,Itatiba,13256700,3120.00
12,2022-04-15 13:09:58.000,103742486137370,Minas Gerais,Coronel Fabriciano,35171208,1200.00
13,2022-04-11 11:39:29.000,103394138035304,Rio de Janeiro,Volta Redonda,27276-190,1000.00
14,2022-04-15 20:18:29.000,103773214419011,Paraná,Maringá,87043-200,350.00
15,2022-04-08 19:31:31.000,103161153444110,Minas Gerais,Uberaba,38080-320,400.00
16,2022-04-11 20:49:49.000,103426600601304,Rio de Janeiro,Volta Redonda,27211040,6667.00
17,2022-04-13 14:02:24.000,103575874949716,São Paulo,São Paulo,02042010,4000.00
18,2022-04-07 21:08:51.000,103082971007172,São Paulo,Poá,08551250,540.00
19,2022-04-10 11:49:46.000,103308713603730,Rio de Janeiro,Rio das Ostras,28890-582,600.00

In [5]:
pedidos['WEIGHT(kg)'] = pedidos['WEIGHT(g)']/1000
pedidos.loc[pedidos['WEIGHT(kg)'] <= 0.1, 'CATEGORIA'] = '0.1'
pedidos.loc[(pedidos['WEIGHT(kg)'] > 0.1) & (pedidos['WEIGHT(kg)'] <= 0.25), 'CATEGORIA'] = '0.25'
pedidos.loc[(pedidos['WEIGHT(kg)'] > 0.25) & (pedidos['WEIGHT(kg)'] <= 0.3), 'CATEGORIA'] = '0.3'
pedidos.loc[(pedidos['WEIGHT(kg)'] > 0.3) & (pedidos['WEIGHT(kg)'] <= 0.5), 'CATEGORIA'] = '0.5'
pedidos.loc[(pedidos['WEIGHT(kg)'] > 0.5) & (pedidos['WEIGHT(kg)'] <= 0.75), 'CATEGORIA'] = '0.75'
pedidos.loc[(pedidos['WEIGHT(kg)'] > 0.75) & (pedidos['WEIGHT(kg)'] <= 1), 'CATEGORIA'] = '1'
pedidos.loc[(pedidos['WEIGHT(kg)'] > 1) & (pedidos['WEIGHT(kg)'] <= 1.25), 'CATEGORIA'] = '1.25'
pedidos.loc[(pedidos['WEIGHT(kg)'] > 1.25) & (pedidos['WEIGHT(kg)'] <= 1.5), 'CATEGORIA'] = '1.5'
pedidos.loc[(pedidos['WEIGHT(kg)'] > 1.5) & (pedidos['WEIGHT(kg)'] <= 2), 'CATEGORIA'] = '2'
pedidos.loc[(pedidos['WEIGHT(kg)'] > 2) & (pedidos['WEIGHT(kg)'] <= 2.5), 'CATEGORIA'] = '2.5'
pedidos.loc[(pedidos['WEIGHT(kg)'] > 2.5) & (pedidos['WEIGHT(kg)'] <= 3), 'CATEGORIA'] = '3'
pedidos.loc[(pedidos['WEIGHT(kg)'] > 3) & (pedidos['WEIGHT(kg)'] <= 3.5), 'CATEGORIA'] = '3.5'
pedidos.loc[(pedidos['WEIGHT(kg)'] > 3.5) & (pedidos['WEIGHT(kg)'] <= 4), 'CATEGORIA'] = '4'
pedidos.loc[(pedidos['WEIGHT(kg)'] > 4) & (pedidos['WEIGHT(kg)'] <= 4.5), 'CATEGORIA'] = '4.5'
pedidos.loc[(pedidos['WEIGHT(kg)'] > 4.5) & (pedidos['WEIGHT(kg)'] <= 5), 'CATEGORIA'] = '5'
pedidos.loc[(pedidos['WEIGHT(kg)'] > 5) & (pedidos['WEIGHT(kg)'] <= 6), 'CATEGORIA'] = '6'
pedidos.loc[(pedidos['WEIGHT(kg)'] > 6) & (pedidos['WEIGHT(kg)'] <= 7), 'CATEGORIA'] = '7'
pedidos.loc[(pedidos['WEIGHT(kg)'] > 7) & (pedidos['WEIGHT(kg)'] <= 7.5), 'CATEGORIA'] = '7.5'
pedidos.loc[(pedidos['WEIGHT(kg)'] > 7.5) & (pedidos['WEIGHT(kg)'] <= 8), 'CATEGORIA'] = '8'
pedidos.loc[(pedidos['WEIGHT(kg)'] > 8) & (pedidos['WEIGHT(kg)'] <= 9), 'CATEGORIA'] = '9'
pedidos.loc[(pedidos['WEIGHT(kg)'] > 9) & (pedidos['WEIGHT(kg)'] <= 10), 'CATEGORIA'] = '10'
pedidos.loc[(pedidos['WEIGHT(kg)'] > 10) & (pedidos['WEIGHT(kg)'] <= 11), 'CATEGORIA'] = '11'
pedidos.loc[(pedidos['WEIGHT(kg)'] > 11) & (pedidos['WEIGHT(kg)'] <= 12), 'CATEGORIA'] = '12'
pedidos.loc[(pedidos['WEIGHT(kg)'] > 12) & (pedidos['WEIGHT(kg)'] <= 13), 'CATEGORIA'] = '13'
pedidos.loc[(pedidos['WEIGHT(kg)'] > 13) & (pedidos['WEIGHT(kg)'] <= 14), 'CATEGORIA'] = '14'
pedidos.loc[(pedidos['WEIGHT(kg)'] > 14) & (pedidos['WEIGHT(kg)'] <= 15), 'CATEGORIA'] = '15'
pedidos.loc[(pedidos['WEIGHT(kg)'] > 15) & (pedidos['WEIGHT(kg)'] <= 16), 'CATEGORIA'] = '16'
pedidos.loc[(pedidos['WEIGHT(kg)'] > 16) & (pedidos['WEIGHT(kg)'] <= 17), 'CATEGORIA'] = '17'
pedidos.loc[(pedidos['WEIGHT(kg)'] > 17) & (pedidos['WEIGHT(kg)'] <= 18), 'CATEGORIA'] = '18'
pedidos.loc[(pedidos['WEIGHT(kg)'] > 18) & (pedidos['WEIGHT(kg)'] <= 19), 'CATEGORIA'] = '19'
pedidos.loc[(pedidos['WEIGHT(kg)'] > 19) & (pedidos['WEIGHT(kg)'] <= 20), 'CATEGORIA'] = '20'
pedidos.loc[(pedidos['WEIGHT(kg)'] > 20) & (pedidos['WEIGHT(kg)'] <= 21), 'CATEGORIA'] = '21'
pedidos.loc[(pedidos['WEIGHT(kg)'] > 21) & (pedidos['WEIGHT(kg)'] <= 22), 'CATEGORIA'] = '22'
pedidos.loc[(pedidos['WEIGHT(kg)'] > 22) & (pedidos['WEIGHT(kg)'] <= 23), 'CATEGORIA'] = '23'
pedidos.loc[(pedidos['WEIGHT(kg)'] > 23) & (pedidos['WEIGHT(kg)'] <= 24), 'CATEGORIA'] = '24'
pedidos.loc[(pedidos['WEIGHT(kg)'] > 24) & (pedidos['WEIGHT(kg)'] <= 25), 'CATEGORIA'] = '25'
pedidos.loc[(pedidos['WEIGHT(kg)'] > 25) & (pedidos['WEIGHT(kg)'] <= 26), 'CATEGORIA'] = '26'
pedidos.loc[(pedidos['WEIGHT(kg)'] > 26) & (pedidos['WEIGHT(kg)'] <= 27), 'CATEGORIA'] = '27'
pedidos.loc[(pedidos['WEIGHT(kg)'] > 27) & (pedidos['WEIGHT(kg)'] <= 28), 'CATEGORIA'] = '28'
pedidos.loc[(pedidos['WEIGHT(kg)'] > 28) & (pedidos['WEIGHT(kg)'] <= 29), 'CATEGORIA'] = '29'
pedidos.loc[(pedidos['WEIGHT(kg)'] > 29) & (pedidos['WEIGHT(kg)'] <= 30), 'CATEGORIA'] = '30'
pedidos

,DATE_TIME,ID,STATE,CITY,ZIPCODE,WEIGHT(g),WEIGHT(kg),CATEGORIA
0,2022-04-11 04:41:39.000,103369596292271,São Paulo,Pirassununga,13638405,176.0,0.176,0.25
1,2022-04-06 12:16:06.000,102958488529312,São Paulo,Praia Grande,11701230,1050.0,1.050,1.25
2,2022-04-17 18:54:41.000,103933822246771,São Paulo,Bauru,17051-080,100.0,0.100,0.1
3,2022-04-06 19:06:49.000,102990666261835,Minas Gerais,Tapiraí,38985000,1334.0,1.334,1.5
4,2022-04-13 21:55:05.000,103598769058125,São Paulo,São Paulo,03258030,1000.0,1.000,1
...,...,...,...,...,...,...,...,...
901691,2022-04-17 16:12:28.000,103931359860582,Minas Gerais,Cabeceira Grande,38625000,400.0,0.400,0.5
901692,2022-04-18 00:34:22.000,103957095496669,São Paulo,Guarulhos,07220010,1450.0,1.450,1.5
901693,2022-04-15 23:24:37.000,103779835356443,Minas Gerais,Unaí,38612-134,500.0,0.500,0.5
901694,2022-04-10 12:39:27.000,103311119142692,Sergipe,Nossa Senhora do Socorro,49160000,500.0,0.500,0.5
901695,2022-04-14 18:40:36.000,103674285528170,São Paulo,São Paulo,04425110,200.0,0.200,0.25

In [6]:
pedidos['PRECO_A'] = 0
pedidos['PRECO_B'] = 0
pedidos

,DATE_TIME,ID,STATE,CITY,ZIPCODE,WEIGHT(g),WEIGHT(kg),CATEGORIA,PRECO_A,PRECO_B
0,2022-04-11 04:41:39.000,103369596292271,São Paulo,Pirassununga,13638405,176.0,0.176,0.25,0,0
1,2022-04-06 12:16:06.000,102958488529312,São Paulo,Praia Grande,11701230,1050.0,1.050,1.25,0,0
2,2022-04-17 18:54:41.000,103933822246771,São Paulo,Bauru,17051-080,100.0,0.100,0.1,0,0
3,2022-04-06 19:06:49.000,102990666261835,Minas Gerais,Tapiraí,38985000,1334.0,1.334,1.5,0,0
4,2022-04-13 21:55:05.000,103598769058125,São Paulo,São Paulo,03258030,1000.0,1.000,1,0,0
...,...,...,...,...,...,...,...,...,...,...
901691,2022-04-17 16:12:28.000,103931359860582,Minas Gerais,Cabeceira Grande,38625000,400.0,0.400,0.5,0,0
901692,2022-04-18 00:34:22.000,103957095496669,São Paulo,Guarulhos,07220010,1450.0,1.450,1.5,0,0
901693,2022-04-15 23:24:37.000,103779835356443,Minas Gerais,Unaí,38612-134,500.0,0.500,0.5,0,0
901694,2022-04-10 12:39:27.000,103311119142692,Sergipe,Nossa Senhora do Socorro,49160000,500.0,0.500,0.5,0,0
901695,2022-04-14 18:40:36.000,103674285528170,São Paulo,São Paulo,04425110,200.0,0.200,0.25,0,0

In [7]:
resultado_a = []
for cep,peso in pedidos.iloc[:, [4, 7]].values:
    cep_limpo = int(cep.replace("-","").replace("'",""))
    linha = carries_a[(cep_limpo >= carries_a['ini_CEP']) & (cep_limpo <= carries_a['fim_CEP'])]
    valor_a = linha.loc[:, peso].values
    resultado_a.append(valor_a)

In [8]:
df_resultado = pd.DataFrame(resultado_a)
df_resultado

                0
0        6.858000
1        8.829657
2        6.858000
3       28.231200
4        7.454661
...           ...
901691  23.241600
901692   8.510400
901693  18.597600
901694  14.331600
901695  18.306000

[901696 rows x 1 columns]

In [9]:
pedidos['PRECO_A'] = df_resultado
pedidos.dtypes

DATE_TIME      object
ID              int64
STATE          object
CITY           object
ZIPCODE        object
WEIGHT(g)     float64
WEIGHT(kg)    float64
CATEGORIA      object
PRECO_A       float64
PRECO_B         int64
dtype: object

In [10]:
resultado_b = []
for cep,peso in pedidos.iloc[:, [4, 7]].values:
    cep_limpo = int(cep.replace("-","").replace("'",""))
    linha = carries_b[(cep_limpo >= carries_b['ini_CEP']) & (cep_limpo <= carries_b['fim_CEP'])]
    valor_b = linha.loc[:, peso].values
    resultado_b.append(valor_b)

In [11]:
df_resultado = pd.DataFrame(resultado_b)
pedidos['PRECO_B'] = df_resultado
pedidos.dtypes

DATE_TIME      object
ID              int64
STATE          object
CITY           object
ZIPCODE        object
WEIGHT(g)     float64
WEIGHT(kg)    float64
CATEGORIA      object
PRECO_A       float64
PRECO_B       float64
dtype: object

In [12]:
pedidos['LEADTIME_A'] = 0
pedidos['LEADTIME_B'] = 0
pedidos.dtypes

DATE_TIME      object
ID              int64
STATE          object
CITY           object
ZIPCODE        object
WEIGHT(g)     float64
WEIGHT(kg)    float64
CATEGORIA      object
PRECO_A       float64
PRECO_B       float64
LEADTIME_A      int64
LEADTIME_B      int64
dtype: object

In [13]:
tempo_entrega_a = []
for cep in pedidos.ZIPCODE.values:
    cep_limpo = int(cep.replace("-","").replace("'",""))
    linha = carries_a[(cep_limpo >= carries_a['ini_CEP']) & (cep_limpo <= carries_a['fim_CEP'])]
    valor_a = linha.lead_time.values
    tempo_entrega_a.append(valor_a)

In [17]:
df_resultado = pd.DataFrame(tempo_entrega_a)
pedidos['LEADTIME_A'] = df_resultado
pedidos.head(40)

,DATE_TIME,ID,STATE,CITY,ZIPCODE,WEIGHT(g),WEIGHT(kg),CATEGORIA,PRECO_A,PRECO_B,LEADTIME_A,LEADTIME_B
0,2022-04-11 04:41:39.000,103369596292271,São Paulo,Pirassununga,13638405,176.00,0.17600,0.25,6.858000,7.687680,4.0,2.0
1,2022-04-06 12:16:06.000,102958488529312,São Paulo,Praia Grande,11701230,1050.00,1.05000,1.25,8.829657,7.680000,4.0,2.0
2,2022-04-17 18:54:41.000,103933822246771,São Paulo,Bauru,17051-080,100.00,0.10000,0.1,6.858000,6.988800,3.0,2.0
3,2022-04-06 19:06:49.000,102990666261835,Minas Gerais,Tapiraí,38985000,1334.00,1.33400,1.5,28.231200,29.586125,5.0,7.0
4,2022-04-13 21:55:05.000,103598769058125,São Paulo,São Paulo,03258030,1000.00,1.00000,1,7.454661,6.748800,2.0,2.0
5,2022-04-18 06:18:51.000,103980705243736,Rio Grande do Sul,Vespasiano Correa,95972000,70.00,0.07000,0.1,20.247085,24.961997,5.0,8.0
6,2022-04-13 08:19:32.000,103553319086609,Minas Gerais,Montes Claros,39402218,562.99,0.56299,0.75,8.484074,7.132800,4.0,3.0
7,2022-04-12 02:12:18.000,103445836489925,Minas Gerais,Itanhandu,37464000,352.00,0.35200,0.5,8.269645,16.390848,6.0,5.0
8,2022-04-06 22:29:07.000,102994528489070,São Paulo,Poá,08554120,400.00,0.40000,0.5,6.858000,7.687680,3.0,2.0
9,2022-04-11 10:32:16.000,103388782855299,Espírito Santo,Linhares,29909290,1000.00,1.00000,1,19.850400,8.416320,6.0,3.0
10,2022-04-09 20:11:29.000,103252314981747,Rondônia,Porto Velho,76810-420,176.00,0.17600,0.25,11.491200,9.916800,6.0,10.0
11,2022-04-14 02:31:20.000,103615312575804,São Paulo,Itatiba,13256700,3120.00,3.12000,3.5,9.547200,12.163800,5.0,2.0
12,2022-04-15 13:09:58.000,103742486137370,Minas Gerais,Coronel Fabriciano,35171208,1200.00,1.20000,1.25,9.476618,8.817600,5.0,3.0
13,2022-04-11 11:39:29.000,103394138035304,Rio de Janeiro,Volta Redonda,27276-190,1000.00,1.00000,1,9.367581,7.094400,7.0,2.0
14,2022-04-15 20:18:29.000,103773214419011,Paraná,Maringá,87043-200,350.00,0.35000,0.5,7.155897,7.488000,3.0,2.0
15,2022-04-08 19:31:31.000,103161153444110,Minas Gerais,Uberaba,38080-320,400.00,0.40000,0.5,8.269645,7.132800,4.0,2.0
16,2022-04-11 20:49:49.000,103426600601304,Rio de Janeiro,Volta Redonda,27211040,6667.00,6.66700,7,14.310000,18.216600,3.0,2.0
17,2022-04-13 14:02:24.000,103575874949716,São Paulo,São Paulo,02042010,4000.00,4.00000,4,7.808400,10.620821,2.0,2.0
18,2022-04-07 21:08:51.000,103082971007172,São Paulo,Poá,08551250,540.00,0.54000,0.75,7.439938,7.687680,3.0,2.0
19,2022-04-10 11:49:46.000,103308713603730,Rio de Janeiro,Rio das Ostras,28890-582,600.00,0.60000,0.75,8.967022,7.803840,4.0,2.0
20,2022-04-15 14:32:34.000,103747009697888,Paraná,Lupionópolis,86635-000,3000.00,3.00000,3,12.184943,34.146432,6.0,4.0
21,2022-04-08 03:09:39.000,103102187272052,São Paulo,São Paulo,03160080,2000.00,2.00000,2,7.743600,7.406688,2.0,2.0
22,2022-04-12 02:34:00.000,103450592146962,Bahia,Riachão do Jacuípe,44640000,1334.00,1.33400,1.5,16.351200,23.549472,9.0,9.0
23,2022-04-18 17:11:44.000,104016719164179,Espírito Santo,Viana,29135372,338.00,0.33800,0.5,8.769600,8.416320,3.0,3.0
24,2022-04-06 22:36:47.000,102995620982257,Minas Gerais,Extrema,37640-000,875.00,0.87500,1,8.698503,7.846080,4.0,3.0
25,2022-04-09 08:55:24.000,103213001299513,Bahia,Poções,45260-000,2232.00,2.23200,2.5,18.673200,27.023712,9.0,10.0
26,2022-04-09 18:48:59.000,103244677198517,São Paulo,Limeira,13487184,562.99,0.56299,0.75,7.609190,6.988800,4.0,2.0
27,2022-04-13 17:04:29.000,103585968432681,Mato Grosso,Alto Taquari,78785000,600.00,0.60000,0.75,29.700000,24.000384,13.0,10.0
28,2022-04-13 22:29:43.000,103602548292726,São Paulo,Santa Isabel,07500000,1000.00,1.00000,1,7.469600,11.379072,3.0,4.0
29,2022-04-07 21:50:19.000,103083830005549,Minas Gerais,Cataguases,36774128,500.00,0.50000,0.5,8.269645,7.846080,6.0,4.0
30,2022-04-10 12:29:40.000,103311581541154,Minas Gerais,Santa Luzia,33080325,6000.00,6.00000,6,13.834800,17.091400,5.0,2.0
31,2022-04-12 17:47:00.000,103496733199613,Minas Gerais,Piracema,35536000,667.00,0.66700,0.75,20.293200,20.811264,9.0,5.0
32,2022-04-08 18:53:29.000,103160002192713,Goiás,Aragoiânia,75330000,495.00,0.49500,0.5,21.978000,17.200320,9.0,8.0
33,2022-04-13 22:48:32.000,103608917065702,São Paulo,São Paulo,02243-000,400.00,0.40000,0.5,6.792540,6.748800,3.0,3.0
34,2022-04-12 17:29:00.000,103500330997928,Pernambuco,Petrolina,56306380,3000.00,3.00000,3,21.570965,11.232000,9.0,7.0
35,2022-04-07 01:40:10.000,103013110075128,São Paulo,Suzano,08690-010,451.00,0.45100,0.5,20.007061,6.988800,7.0,2.0
36,2022-04-08 06:02:01.000,103113902290455,Rio de Janeiro,Rio de Janeiro,22780085,400.00,0.40000,0.5,6.890928,6.720000,2.0,2.0
37,2022-04-15 11:08:24.000,103734879975046,Rio de Janeiro,Mesquita,26570100,500.00,0.50000,0.5,7.310482,7.803840,4.0,4.0
38,2022-04-11 23:22:31.000,103430055439711,Tocantins,Palmas,77022096,40.00,0.04000,0.1,8.370000,9.379200,6.0,6.0
39,2022-04-12 21:42:07.000,103516646135974,Tocantins,Palmas,77006738,400.00,0.40000,0.5,9.394522,9.379200,6.0,6.0

In [15]:
tempo_entrega_b = []
for cep in pedidos.ZIPCODE.values:
    cep_limpo = int(cep.replace("-","").replace("'",""))
    linha = carries_b[(cep_limpo >= carries_b['ini_CEP']) & (cep_limpo <= carries_b['fim_CEP'])]
    valor_b = linha.lead_time.values
    tempo_entrega_b.append(valor_b)

In [16]:
df_resultado = pd.DataFrame(tempo_entrega_b)
pedidos['LEADTIME_B'] = df_resultado
pedidos.head(40)

,DATE_TIME,ID,STATE,CITY,ZIPCODE,WEIGHT(g),WEIGHT(kg),CATEGORIA,PRECO_A,PRECO_B,LEADTIME_A,LEADTIME_B
0,2022-04-11 04:41:39.000,103369596292271,São Paulo,Pirassununga,13638405,176.00,0.17600,0.25,6.858000,7.687680,0,2.0
1,2022-04-06 12:16:06.000,102958488529312,São Paulo,Praia Grande,11701230,1050.00,1.05000,1.25,8.829657,7.680000,0,2.0
2,2022-04-17 18:54:41.000,103933822246771,São Paulo,Bauru,17051-080,100.00,0.10000,0.1,6.858000,6.988800,0,2.0
3,2022-04-06 19:06:49.000,102990666261835,Minas Gerais,Tapiraí,38985000,1334.00,1.33400,1.5,28.231200,29.586125,0,7.0
4,2022-04-13 21:55:05.000,103598769058125,São Paulo,São Paulo,03258030,1000.00,1.00000,1,7.454661,6.748800,0,2.0
5,2022-04-18 06:18:51.000,103980705243736,Rio Grande do Sul,Vespasiano Correa,95972000,70.00,0.07000,0.1,20.247085,24.961997,0,8.0
6,2022-04-13 08:19:32.000,103553319086609,Minas Gerais,Montes Claros,39402218,562.99,0.56299,0.75,8.484074,7.132800,0,3.0
7,2022-04-12 02:12:18.000,103445836489925,Minas Gerais,Itanhandu,37464000,352.00,0.35200,0.5,8.269645,16.390848,0,5.0
8,2022-04-06 22:29:07.000,102994528489070,São Paulo,Poá,08554120,400.00,0.40000,0.5,6.858000,7.687680,0,2.0
9,2022-04-11 10:32:16.000,103388782855299,Espírito Santo,Linhares,29909290,1000.00,1.00000,1,19.850400,8.416320,0,3.0
10,2022-04-09 20:11:29.000,103252314981747,Rondônia,Porto Velho,76810-420,176.00,0.17600,0.25,11.491200,9.916800,0,10.0
11,2022-04-14 02:31:20.000,103615312575804,São Paulo,Itatiba,13256700,3120.00,3.12000,3.5,9.547200,12.163800,0,2.0
12,2022-04-15 13:09:58.000,103742486137370,Minas Gerais,Coronel Fabriciano,35171208,1200.00,1.20000,1.25,9.476618,8.817600,0,3.0
13,2022-04-11 11:39:29.000,103394138035304,Rio de Janeiro,Volta Redonda,27276-190,1000.00,1.00000,1,9.367581,7.094400,0,2.0
14,2022-04-15 20:18:29.000,103773214419011,Paraná,Maringá,87043-200,350.00,0.35000,0.5,7.155897,7.488000,0,2.0
15,2022-04-08 19:31:31.000,103161153444110,Minas Gerais,Uberaba,38080-320,400.00,0.40000,0.5,8.269645,7.132800,0,2.0
16,2022-04-11 20:49:49.000,103426600601304,Rio de Janeiro,Volta Redonda,27211040,6667.00,6.66700,7,14.310000,18.216600,0,2.0
17,2022-04-13 14:02:24.000,103575874949716,São Paulo,São Paulo,02042010,4000.00,4.00000,4,7.808400,10.620821,0,2.0
18,2022-04-07 21:08:51.000,103082971007172,São Paulo,Poá,08551250,540.00,0.54000,0.75,7.439938,7.687680,0,2.0
19,2022-04-10 11:49:46.000,103308713603730,Rio de Janeiro,Rio das Ostras,28890-582,600.00,0.60000,0.75,8.967022,7.803840,0,2.0
20,2022-04-15 14:32:34.000,103747009697888,Paraná,Lupionópolis,86635-000,3000.00,3.00000,3,12.184943,34.146432,0,4.0
21,2022-04-08 03:09:39.000,103102187272052,São Paulo,São Paulo,03160080,2000.00,2.00000,2,7.743600,7.406688,0,2.0
22,2022-04-12 02:34:00.000,103450592146962,Bahia,Riachão do Jacuípe,44640000,1334.00,1.33400,1.5,16.351200,23.549472,0,9.0
23,2022-04-18 17:11:44.000,104016719164179,Espírito Santo,Viana,29135372,338.00,0.33800,0.5,8.769600,8.416320,0,3.0
24,2022-04-06 22:36:47.000,102995620982257,Minas Gerais,Extrema,37640-000,875.00,0.87500,1,8.698503,7.846080,0,3.0
25,2022-04-09 08:55:24.000,103213001299513,Bahia,Poções,45260-000,2232.00,2.23200,2.5,18.673200,27.023712,0,10.0
26,2022-04-09 18:48:59.000,103244677198517,São Paulo,Limeira,13487184,562.99,0.56299,0.75,7.609190,6.988800,0,2.0
27,2022-04-13 17:04:29.000,103585968432681,Mato Grosso,Alto Taquari,78785000,600.00,0.60000,0.75,29.700000,24.000384,0,10.0
28,2022-04-13 22:29:43.000,103602548292726,São Paulo,Santa Isabel,07500000,1000.00,1.00000,1,7.469600,11.379072,0,4.0
29,2022-04-07 21:50:19.000,103083830005549,Minas Gerais,Cataguases,36774128,500.00,0.50000,0.5,8.269645,7.846080,0,4.0
30,2022-04-10 12:29:40.000,103311581541154,Minas Gerais,Santa Luzia,33080325,6000.00,6.00000,6,13.834800,17.091400,0,2.0
31,2022-04-12 17:47:00.000,103496733199613,Minas Gerais,Piracema,35536000,667.00,0.66700,0.75,20.293200,20.811264,0,5.0
32,2022-04-08 18:53:29.000,103160002192713,Goiás,Aragoiânia,75330000,495.00,0.49500,0.5,21.978000,17.200320,0,8.0
33,2022-04-13 22:48:32.000,103608917065702,São Paulo,São Paulo,02243-000,400.00,0.40000,0.5,6.792540,6.748800,0,3.0
34,2022-04-12 17:29:00.000,103500330997928,Pernambuco,Petrolina,56306380,3000.00,3.00000,3,21.570965,11.232000,0,7.0
35,2022-04-07 01:40:10.000,103013110075128,São Paulo,Suzano,08690-010,451.00,0.45100,0.5,20.007061,6.988800,0,2.0
36,2022-04-08 06:02:01.000,103113902290455,Rio de Janeiro,Rio de Janeiro,22780085,400.00,0.40000,0.5,6.890928,6.720000,0,2.0
37,2022-04-15 11:08:24.000,103734879975046,Rio de Janeiro,Mesquita,26570100,500.00,0.50000,0.5,7.310482,7.803840,0,4.0
38,2022-04-11 23:22:31.000,103430055439711,Tocantins,Palmas,77022096,40.00,0.04000,0.1,8.370000,9.379200,0,6.0
39,2022-04-12 21:42:07.000,103516646135974,Tocantins,Palmas,77006738,400.00,0.40000,0.5,9.394522,9.379200,0,6.0

Empty DataFrame
Columns: [DATE_TIME, ID, STATE, CITY, ZIPCODE, WEIGHT(g), WEIGHT(kg), CATEGORIA, PRECO_A, PRECO_B, LEADTIME_A, LEADTIME_B]
Index: []

In [30]:
pedidos.to_csv('pedidos_tratados.csv', index = False)

*Resultados esperados*
Como resultados esperamos:

•	Definição do melhor custo médio por pacote e tempo de entrega utilizando a melhor combinação de alocação entre os concorrentes;

•	Porcentagem e custo médio dos pedidos transportados por cada parceiro.

Dica: Faça uma análise considerando cada critério entre custo e tempo de entrega.

•	Melhor custo / tempo de entrega por cidade e estado.

•	Fração de pedidos cobertos pelas transportadoras propostas.